"""Add binary image field to BluechipData

Revision ID: 14a87445306b
Revises: dcd1bb7f188f
Create Date: 2024-11-07 17:01:56.003383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14a87445306b'
down_revision = 'dcd1bb7f188f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bluechip_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.LargeBinary(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bluechip_data', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
