"""Add Agent  models

Revision ID: 33817b17cd42
Revises: 822d554328c0
Create Date: 2024-11-04 10:44:09.202673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33817b17cd42'
down_revision = '822d554328c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adhaar_pasprt', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('gst', sa.String(length=15), nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=False))
        batch_op.create_unique_constraint(None, ['gst'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('address')
        batch_op.drop_column('gst')
        batch_op.drop_column('adhaar_pasprt')

    # ### end Alembic commands ###
