"""Drop columns from students table

Revision ID: 34a361130b81
Revises: 7f5fb76a0fbf
Create Date: 2024-10-29 15:42:57.894549

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '34a361130b81'
down_revision = '7f5fb76a0fbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('degree_transcript')
        batch_op.drop_column('prefered_university')
        batch_op.drop_column('special_request')
        batch_op.drop_column('prefered_intake')
        batch_op.drop_column('budget')
        batch_op.drop_column('passport_copy')
        batch_op.drop_column('diploma_certificate')
        batch_op.drop_column('statement_of_purpose')
        batch_op.drop_column('career_gap')
        batch_op.drop_column('prefered_country')
        batch_op.drop_column('resume')
        batch_op.drop_column('experience_letter')
        batch_op.drop_column('letter_of_recommendation')
        batch_op.drop_column('tenth_marksheet')
        batch_op.drop_column('twelfth_marksheet')
        batch_op.drop_column('course_completion_certificate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_completion_certificate', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('twelfth_marksheet', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('tenth_marksheet', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('letter_of_recommendation', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('experience_letter', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('resume', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('prefered_country', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('career_gap', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('statement_of_purpose', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('diploma_certificate', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('passport_copy', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('budget', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('prefered_intake', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('special_request', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('prefered_university', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('degree_transcript', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
