"""Description of the change

Revision ID: 548cd2b8ad6a
Revises: 82b75afcc12b
Create Date: 2024-11-08 11:50:14.082255

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '548cd2b8ad6a'
down_revision = '82b75afcc12b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('universities', schema=None) as batch_op:
        batch_op.alter_column('fees',
               existing_type=mysql.FLOAT(),
               type_=mysql.LONGBLOB(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('universities', schema=None) as batch_op:
        batch_op.alter_column('fees',
               existing_type=mysql.LONGBLOB(),
               type_=mysql.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###
