"""Add document and preference fields to Student model

Revision ID: 7f5fb76a0fbf
Revises: 443016c2cfe4
Create Date: 2024-10-29 12:44:38.589058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f5fb76a0fbf'
down_revision = '443016c2cfe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('passport_copy', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('tenth_marksheet', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('twelfth_marksheet', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('degree_transcript', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('diploma_certificate', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('course_completion_certificate', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('letter_of_recommendation', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('experience_letter', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('statement_of_purpose', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('prefered_university', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('prefered_country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('prefered_intake', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('budget', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('career_gap', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('special_request', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('special_request')
        batch_op.drop_column('career_gap')
        batch_op.drop_column('budget')
        batch_op.drop_column('prefered_intake')
        batch_op.drop_column('prefered_country')
        batch_op.drop_column('prefered_university')
        batch_op.drop_column('statement_of_purpose')
        batch_op.drop_column('experience_letter')
        batch_op.drop_column('letter_of_recommendation')
        batch_op.drop_column('course_completion_certificate')
        batch_op.drop_column('diploma_certificate')
        batch_op.drop_column('degree_transcript')
        batch_op.drop_column('twelfth_marksheet')
        batch_op.drop_column('tenth_marksheet')
        batch_op.drop_column('passport_copy')
        batch_op.drop_column('resume')

    # ### end Alembic commands ###
