"""Add country_st and university_st to student

Revision ID: a44d42c6b152
Revises: 4686e573aa39
Create Date: 2024-11-12 12:46:50.433256

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a44d42c6b152'
down_revision = '4686e573aa39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country_st', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('university_st', sa.String(length=100), nullable=True))
        batch_op.drop_column('university')
        batch_op.drop_column('country')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('university', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('university_st')
        batch_op.drop_column('country_st')

    # ### end Alembic commands ###
