"""Add marksheet_10 and marks_12 fields to Student table

Revision ID: a591037c84ce
Revises: f15797d96fd3
Create Date: 2024-10-30 23:02:52.733250

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a591037c84ce'
down_revision = 'f15797d96fd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('marksheet_10',
               existing_type=sa.BLOB(),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
        batch_op.alter_column('marks_12',
               existing_type=sa.BLOB(),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('marks_12',
               existing_type=mysql.LONGBLOB(),
               type_=sa.BLOB(),
               existing_nullable=True)
        batch_op.alter_column('marksheet_10',
               existing_type=mysql.LONGBLOB(),
               type_=sa.BLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###
