"""Remove resume and passport_copy columns from students table

Revision ID: ae12efd8480c
Revises: a03064a1e991
Create Date: 2024-10-30 10:57:08.200191

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ae12efd8480c'
down_revision = 'a03064a1e991'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('resume',
               existing_type=sa.BLOB(),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
        batch_op.alter_column('passport_copy',
               existing_type=sa.BLOB(),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('passport_copy',
               existing_type=mysql.LONGBLOB(),
               type_=sa.BLOB(),
               existing_nullable=True)
        batch_op.alter_column('resume',
               existing_type=mysql.LONGBLOB(),
               type_=sa.BLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###
