"""Fix relationship between Agent and AgentDoc

Revision ID: dcd1bb7f188f
Revises: 33817b17cd42
Create Date: 2024-11-04 23:00:24.897248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcd1bb7f188f'
down_revision = '33817b17cd42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents_doc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agent_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'agents', ['agent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents_doc', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('agent_id')

    # ### end Alembic commands ###
