"""Add marksheet_10 and marks_12 fields to Student table

Revision ID: f15797d96fd3
Revises: ae12efd8480c
Create Date: 2024-10-30 22:59:57.199465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f15797d96fd3'
down_revision = 'ae12efd8480c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marksheet_10', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('marks_12', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('marks_12')
        batch_op.drop_column('marksheet_10')

    # ### end Alembic commands ###
